### ISSUE TITLE
Blackfire Image / Probe Outdated

### ISSUE THREAD

**Issue by sprankhub** [wardenenv/images#14] opened 2023-09-21 09:50 UTC
When using Blackfire after running `warden env pull && warden env up`, a warning is shown in Blackfire:

![image](https://github.com/wardenenv/images/assets/930199/11d929fe-ae6c-436f-b7ad-8f7251589cf5)

> This profile was generated with an outdated Blackfire Probe

So the used version of the Blackfire Probe is 1.86.4, even though the latest version is 1.89.0 according to https://blackfire.io/docs/up-and-running/update.

https://hub.docker.com/r/wardenenv/php-fpm/tags?page=1&name=8.1-magento2-blackfire shows that the Blackfire image has last been pushed six months ago. Sounds suspicious?

**Comment by navarr** [comment] 2024-01-03 15:49
Current Blackfire Probe in PHP is 1.92.4 - that is one patch version out of date (1.92.5) but that should be fixed with the most recent rebuild.

This was caused by PHP not rebuilding daily, which it has now been scheduled to do.

**Closed by navarr** 2024-01-03 15:49 UTC
